version: '3.1'

services:
  db:
    container_name: y_social_net_db
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password 
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
