apiVersion: v1
kind: Service
metadata:
  name: y-postgres-cluster-loadbalancer-nodeport
spec:
  type: NodePort
  selector:
    app: y-postgres-cluster-loadbalancer
  ports:
    - protocol: TCP
      port: 5432  
      targetPort: 9999  
      nodePort: 30001  

