apiVersion: v1
kind: Service
metadata:
  name: y-postgres-cluster-loadbalancer-service
spec:
  selector:
    app: y-postgres-cluster-loadbalancer
  ports:
    - protocol: TCP
      port: 5432  
      targetPort: 9999

